"""
PDF Report Export Module - Generate professional PDF reports
Exports analysis results as downloadable PDF documents
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

REPORTS_DIR = "disease_reports"

def ensure_reports_dir():
    """Ensure reports directory exists"""
    if not os.path.exists(REPORTS_DIR):
        os.makedirs(REPORTS_DIR)

def generate_analysis_report(
    username, 
    disease_name, 
    confidence, 
    severity,
    treatment,
    description,
    image_path=None,
    lang="en"
):
    """
    Generate a professional PDF report of disease analysis
    """
    ensure_reports_dir()
    
    # Create filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{REPORTS_DIR}/{username}_report_{timestamp}.pdf"
    
    # Create PDF document
    doc = SimpleDocTemplate(filename, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#2E7D32"),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#43A047"),
        spaceAfter=12,
        fontName='Helvetica-Bold'
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=10,
        alignment=TA_LEFT
    )
    
    # Title
    title = Paragraph("🌾 Crop Disease Analysis Report", title_style)
    story.append(title)
    story.append(Spacer(1, 0.2*inch))
    
    # Report metadata
    metadata_data = [
        ["Report Generated:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["User:", username],
        ["Disease Detected:", disease_name],
        ["Confidence Level:", f"{confidence*100:.1f}%"],
        ["Severity:", severity]
    ]
    
    metadata_table = Table(metadata_data, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#E8F5E9")),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#CCCCCC")),
    ]))
    
    story.append(metadata_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Disease Description
    story.append(Paragraph("Disease Information", heading_style))
    story.append(Paragraph(description, normal_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Treatment Recommendations
    story.append(Paragraph("Treatment Recommendations", heading_style))
    story.append(Paragraph(treatment, normal_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Severity Assessment
    severity_colors = {
        "Low": colors.HexColor("#4CAF50"),
        "Medium": colors.HexColor("#FFA500"),
        "High": colors.HexColor("#FF6B6B")
    }
    
    story.append(Paragraph("Severity Assessment", heading_style))
    severity_assessment = f"""Severity Level: {severity}

This disease has been classified as having a {severity.lower()} severity level.
Please take appropriate action based on the treatment recommendations above."""
    story.append(Paragraph(severity_assessment, normal_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Confidence Explanation
    story.append(Paragraph("Analysis Confidence", heading_style))
    
    if confidence >= 0.9:
        confidence_text = "Very High - The AI model is very confident in this diagnosis"
    elif confidence >= 0.8:
        confidence_text = "High - The AI model is confident in this diagnosis"
    elif confidence >= 0.7:
        confidence_text = "Medium - The AI model is reasonably confident, but expert consultation is recommended"
    else:
        confidence_text = "Low - For better accuracy, try uploading a clearer image"
    
    story.append(Paragraph(
        f"Confidence Score: {confidence*100:.1f}% - {confidence_text}",
        normal_style
    ))
    story.append(Spacer(1, 0.3*inch))
    
    # Footer
    footer_text = f"""
    This report is generated by the Crop Disease Detection system.
    For expert advice, please consult with agricultural professionals.
    
    Report ID: {timestamp}
    """
    story.append(Paragraph(footer_text, normal_style))
    
    # Build PDF
    try:
        doc.build(story)
        return filename
    except Exception as e:
        print(f"Error generating PDF: {e}")
        return None

def get_user_reports(username):
    """Get list of all reports for a user"""
    ensure_reports_dir()
    
    user_reports = []
    for filename in os.listdir(REPORTS_DIR):
        if filename.startswith(f"{username}_report_"):
            filepath = os.path.join(REPORTS_DIR, filename)
            file_size = os.path.getsize(filepath) / 1024  # Size in KB
            mod_time = datetime.fromtimestamp(os.path.getmtime(filepath))
            user_reports.append({
                'filename': filename,
                'filepath': filepath,
                'size': f"{file_size:.1f} KB",
                'date': mod_time.strftime("%Y-%m-%d %H:%M:%S")
            })
    
    # Sort by date, newest first
    user_reports.sort(key=lambda x: x['date'], reverse=True)
    return user_reports

def delete_report(filepath):
    """Delete a specific report"""
    try:
        if os.path.exists(filepath):
            os.remove(filepath)
            return True
    except Exception as e:
        print(f"Error deleting report: {e}")
    return False

def cleanup_old_reports(username, keep_count=10):
    """Keep only the most recent reports for a user"""
    user_reports = get_user_reports(username)
    
    if len(user_reports) > keep_count:
        # Delete oldest reports
        for report in user_reports[keep_count:]:
            delete_report(report['filepath'])
